### ISSUE TITLE
Thanks for your works! Can you show us your trainset?

### ISSUE THREAD

**Issue by kfchenhn** [richard-peng-xia/RULE#1]

**Comment by bhosalems** [comment]
Yes, any timeline on the release of the training dataset please?

**Comment by richard-peng-xia** [comment]
Hi @kfchenhn @bhosalems ,

Sorry for the late response. We will release the whole dataset asap. It may be delayed a bit as we are working on tight ddl.

Apologize for it again.

**Comment by richard-peng-xia** [comment]
The dataset is released!
