### ISSUE TITLE
trainDataSet

### ISSUE THREAD

**Issue by 15838271393lyc** [richard-peng-xia/RULE#2]
Hello author，Can you provide us with you trainingSet?

**Comment by bhosalems** [comment]
Yes, any timeline on the release of the training dataset, please?

**Comment by richard-peng-xia** [comment]
Hi, @bhosalems @15838271393lyc .

Sorry for the late response. We will release the whole dataset asap. It may be delayed a bit as we are working on tight ddl.

Apologize for it again.

**Comment by ahmadmustafaanis** [comment]
Looking forward to the training dataset

**Comment by kfchenhn** [comment]
Looking forward to the training dataset

**Comment by richard-peng-xia** [comment]
The dataset is released!
