### ISSUE TITLE
Release RULE on Hugging Face (with gated access)

### ISSUE THREAD

**Issue by NielsRogge** [richard-peng-xia/RULE#5]
Hi @richard-peng-xia,

Niels here from the open-source team at Hugging Face. I discovered your work through EMNLP, congrats on getting it accepted! I indexed the paper here: https://huggingface.co/papers/2407.05131 (feel free to claim it with your HF account). I work together with [AK](https://x.com/_akhaliq) on improving the visibility of researchers' work on the hub.

It'd be great to make the dataset available on the 🤗 hub, rather than Github, to improve the visibility/discoverability of your work. We can add tags so that people find them when filtering https://huggingface.co/datasets, so that people can do:

```python
from datasets import load_dataset

dataset = load_dataset("your-hf-username-or-organization/your-dataset")
```

See here for a guide: https://huggingface.co/docs/datasets/image_dataset.

There's then also the dataset viewer which allows people to see the first few rows in the browser: https://huggingface.co/docs/hub/en/datasets-viewer.

This would make the dataset easier accessible, and also discoverable. We can then also link the dataset to the paper page.

## Gating mechanism

We support gating (similar to how this works for llama/mistral models), so that you can manually review who can access the dataset: https://huggingface.co/docs/hub/en/datasets-gated. See FineVideo (a video dataset created by HF) as an example: https://huggingface.co/datasets/HuggingFaceFV/finevideo.

Let us know if you need any help.

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by NielsRogge** [comment]
Hi @richard-peng-xia any reason to close this issue?

**Comment by richard-peng-xia** [comment]
Hi @NielsRogge,

We will reopen this issue when we have prepared all the data and model checkpoints. Thanks.

**Comment by NielsRogge** [comment]
Thanks, would it be possible to keep the issue open as otherwise it might get lost?
