### ISSUE TITLE
Request for a Cleaner Format of the QA Test Dataset

### ISSUE THREAD

**Issue by CC-aff** [richard-peng-xia/RULE#6]
https://github.com/richard-peng-xia/RULE/blob/f1bf7f7020918faab49e2dff12e01e7de41821bb/data/test/harvard_test.jsonl#L2-L4

Hi,

I’ve noticed that the current QA test dataset contains some responses that are not in a clean "yes/no" format. Is there a possibility of providing a more standardized dataset with a clearer format for the answers?

Thanks!

**Comment by richard-peng-xia** [comment]
Hi @CC-aff ,

Sorry to bother you. The VQA datasets are obtained through GPT-4 based on medical reports. We will update an cleaner version later.

Thanks.
