### ISSUE TITLE
why the performer is so lower?

### ISSUE THREAD

**Issue by xinyunxing** [richard-peng-xia/RULE#7]
Acuracy:0.53
F1 Score:0.67
AUC:0.5185

I  follow you Readmi  docment,why the performer is so lower?

**Comment by richard-peng-xia** [comment]
Hi @xinyunxing ,

Could you give more details about your experiment? e.g., datasets, training details

Even the original model (LLaVA-Med-1.5) outperforms than Acc 0.53.

Thanks.

**Comment by xinyunxing** [comment]
first:
    --master_port=12350 \ 
    -m training.main \
    --model hf-hub:thaottn/OpenCLIP-resnet50-CC12M \
    --train-data '/data/quan/RULE/data/training/retriever/harvard_train.json' \
    --dataset-type Harvard\
    --img_root /data/mm/Harvard/dataset\
    --batch-size 256 \
    --precision amp \
    --workers 4 \
    --lr 0.0001 \
    --epochs 360 \
    --val-data "/data/quan/RULE/data/training/retriever/harvard_val.json" \
    --val-frequency 10 \
    --report-to tensorboard \
    --logs /data/quan/RULE/retriver_save
second: CUDA_VISIBLE_DEVICES=1 python /data/quan/RULE/retrieve/src/retrieve_clip_VQA.py \
    --img_root /data/mm/Harvard/dataset \
    --train_json /data/quan/RULE/data/training/retriever/harvard_train.json \
    --eval_json /data/quan/RULE/data/training/retriever/harvard_val.json \
    --model_name_or_path hf-hub:thaottn/OpenCLIP-resnet50-CC12M \
    --checkpoint_path /data/quan/RULE/retriver_save/360-model_hf-hub:thaottn-OpenCLIP-resnet50-CC12M-lr_0.0001-b_256-j_4-p_amp/checkpoints/epoch_360.pt \
    --output_path /data/quan/RULE/retriver_clip_save/out.json \
    --fixed_k 5 \
third : CUDA_VISIBLE_DEVICES='0,1,2,3,4,5,6' deepspeed --include localhost:0,1,2,3,4,5,6 /data/quan/RULE/llava/train/train_dpo.py \
    --model_name_or_path /data/quan/MMed-RAG2/llava-med-v1.5-mistral-7b \
    --deepspeed ./scripts/zero3.json \
    --version v1 \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 \
    --data_path /data/quan/RULE/data/training/alignment/harvard.json \
    --image_folder /data/mm/Harvard/dataset\
    --vision_tower openai/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir /data/quan/RULE/save \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1\
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 200 \
    --save_total_limit 1 \
    --learning_rate 1e-7 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to wandb \
    --tf32 True \
    --model_max_length 1024 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
Four:export CUDA_VISIBLE_DEVICES=7
dataset='harvard'   #'iuxray' # 'harvard' 'mimic'

python llava/eval/model_vqa_${dataset}.py \
    --model-base /data/quan/MMed-RAG2/llava-med-v1.5-mistral-7b \
    --model-path /data/quan/RULE/save\
    --question-file /data/quan/RULE/data/test/harvard_test.jsonl \
    --image-folder /data/mm/Harvard/dataset1/Test \
    --answers-file /data/quan/RULE/answer_save/answer.jsonl

**Comment by xinyunxing** [comment]
what error have  this?

**Comment by richard-peng-xia** [comment]
Following your scripts, do you curate the corresponding preference data based on the over-reliance issue introduced by RAG?

**Comment by richard-peng-xia** [comment]
BTW, have you tried to do more detailed ablation experiments? Based on your scripts, we cannot find your problems.

**Comment by xinyunxing** [comment]
"Where in your file is the operation for curating the corresponding preference data based on the over-reliance issue introduced by RAG?"

**Comment by xinyunxing** [comment]
In your code, k is fixed to a value of 5. How can we make it adaptive?

**Comment by richard-peng-xia** [comment]
- If you even do not prepare the preference data, how do you conduct the preference tuning? For this part, you can refer to our paper.
- About adaptive-k, please refer to [our another repo](https://github.com/richard-peng-xia/MMed-RAG).

**Comment by xinyunxing** [comment]
关于偏好数据集，我是采用的您提供/data/quan/MMed-RAG3/data/training/alignment/ophthalmology/harvard_vqa.json 
![image](https://github.com/user-attachments/assets/3de358bf-361e-49e6-9769-14eb7c912e67)
，然后运行/data/quan/MMed-RAG3/scripts/train_dpo_2stages.sh，但我发现这里好像没把外部检索器放在里面一起做微调.Readmi 里面好像没写的很清楚。

**Comment by richard-peng-xia** [comment]
我们提供的是原始数据，偏好数据需要通过加入检索后的结果对比挑选出。如果你没有生成偏好数据，你是如何进行DPO微调的？
