### ISSUE TITLE
Questions About Report Generation Prompts and Evaluation Scripts

### ISSUE THREAD

**Issue by Jack-ZC8** [richard-peng-xia/RULE#8]
Hello,
First, I want to thank you for the wonderful work on this project—it's truly appreciated!

I have a couple of quick questions:
1. Could you please share the prompts used for report generation in your work?
2. Could you please share any scripts for evaluating generated reports using BLEU, ROUGE-L, and METEOR?

I really appreciate your help!

**Comment by richard-peng-xia** [comment]
Thanks for your attention.

- Our prompt for report generation task is `Please generate a report based on the input medical image.`
- We will upload the corresponding code for metrics further. Simply put, we used tools like NLTK and rouge_score to calculate the metrics.

**Comment by Jack-ZC8** [comment]
Thanks, it helps a lot!
