### ISSUE TITLE
Discrepancies in Baseline Reproduction

### ISSUE THREAD

**Issue by Jack-ZC8** [richard-peng-xia/RULE#9]
I apologize for reaching out again. I am trying to reproduce the basic baselines reported in the paper (temperature=0.2 and temperature=0). I’ve compared the results and found significant discrepancies in two cases. I would appreciate any insights you could provide.

| Acc        | IU-Xray | Harvard-FairVLMed | MIMIC-CXR |
|------------|---------|--------------------|-----------|
| T=0.2 (Reported)   | 75.47   | 63.03              | 75.79     |
| T=0.2 (Reproduced) | 78.00   | 62.94              | 75.99     |
| T=0 (Reported)     | 76.88   | 78.32              | 82.54     |
| T=0 (Reproduced)   | 78.43   | **62.43**              | **76.20**     |

I used the following inference command:
```bash
for dataset in "harvard" "iuxray" "mimic"
do
    python llava/eval/model_vqa_${dataset}.py \
        --model-path data/llava-med-v1.5-mistral-7b \
        --question-file data/test/${dataset}_test.jsonl \
        --image-folder data/medical_images/${dataset} \
        --answers-file alog/temperature=0/${dataset}.json \
        --temperature 0 #0.2
done
```

- The inference results were uploaded [here](https://drive.google.com/file/d/1FgD6kcsfjFCIxB6sbdzjBT8CtHSOYAQ9/view?usp=drive_link).
- The scoring script used is based on [eval_yesno.py](https://github.com/richard-peng-xia/CARES/blob/main/src/eval/eval_yesno.py) from the CARES repository, and it was uploaded [here](https://drive.google.com/file/d/18XFOyu37VMqkGKtO5Pq1IePnY0W4AGyM/view?usp=sharing).

I sincerely hope to receive some insights on this matter. Thank you very much for your help!

**Comment by richard-peng-xia** [comment]
Thanks for your questions.

- In our experiments, the temperature was set to 0. In fact, we observed that the model's performance was highly unstable during our experiments, especially for closed-ended questions. 
- Additionally, the results you provided (third row) are from greedy decoding, not the basic baseline results. Based on our experience, we strongly discourage further improvements on decoding-based methods, as these approaches are extremely time-consuming and yield very limited improvements.

**Comment by Jack-ZC8** [comment]
Thanks, it helps a lot!
